federation_version: 2.10

subgraphs:
  repo-agent:
    routing_url: http://localhost:3004/graphql
    schema:
      file: ./repo-agent-schema.graphql
  claude:
    routing_url: http://localhost:3002/graphql
    schema:
      file: ./claude-schema.graphql