sources:
  - name: repo-agent
    handler:
      graphql:
        endpoint: http://localhost:3004/graphql
        
  - name: claude
    handler:
      graphql:
        endpoint: http://localhost:3002/graphql
  
  - name: GitHubREST
    handler:
      openapi:
        source: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
        operationHeaders:
          Authorization: Bearer {env.GITHUB_TOKEN}
          Accept: application/vnd.github.v3+json
    transforms:
      - prefix:
          value: GitHub_
      - namingConvention:
          typeNames: pascalCase
          fieldNames: camelCase
          enumValues: upperCase

serve:
  port: 3000
  cors:
    origin: true
    credentials: true
  playground: true

# Cache configuration would go here but needs proper setup