# Cosmo Router Configuration for Local Development
version: "1"

# Development mode settings
dev_mode: true

# Graph configuration - using introspection for local dev
graph:
  # Sign the JWT token with a local secret for development
  token:
    # This is a development-only token
    secret: "cosmo-development-secret-do-not-use-in-production"

# Engine configuration  
engine:
  datasource_cache_size: 10

# Server configuration
listen_addr: "localhost:4000"
playground_enabled: true
introspection_enabled: true

# CORS settings
cors:
  enabled: true
  allow_origins:
    - "http://localhost:3001"
    - "http://localhost:3000"
    - "http://localhost:5173"
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - "*"
  allow_credentials: true
  max_age: 86400

# Subscriptions
subscriptions:
  enabled: true
  protocols:
    - graphql-ws
    - graphql-sse
    
# Subgraphs for local development
subgraphs:
  - id: "claude"
    name: "claude"
    routing_url: "http://localhost:3002/graphql"
    subscription_url: "http://localhost:3002/graphql"
    subscription_protocols:
      - "graphql-ws"
    schema_polling_interval: 30s
  
  - id: "git"
    name: "git"  
    routing_url: "http://localhost:3004/graphql"
    subscription_url: "http://localhost:3004/graphql"
    subscription_protocols:
      - "graphql-ws"
    schema_polling_interval: 30s
    
  - id: "github"
    name: "github"
    routing_url: "http://localhost:3005/graphql"
    schema_polling_interval: 30s

# Headers configuration
headers:
  all:
    propagate:
      - name: "x-correlation-id"
      - name: "authorization"
        
# Health check configuration
health_check_path: "/health"
ready_check_path: "/ready"

# Telemetry
telemetry:
  metrics:
    prometheus:
      enabled: true
      listen_addr: "localhost:8088"
      path: "/metrics"
  tracing:
    enabled: false

# Router development features
router_config_path: ""
execution_config:
  request_timeout: 30s
  enable_request_tracing: true

# Rate limiting
rate_limit:
  enabled: false  # Disabled for local dev
  
# Request logging for development
request_logging:
  enabled: true
  level: "info"