version: 1
subgraphs:
  - name: claude-service
    routing_url: http://localhost:3002/graphql
    subscription:
      url: http://localhost:3002/graphql/stream
      protocol: sse
  - name: git-service  
    routing_url: http://localhost:3003/graphql
    subscription:
      url: http://localhost:3003/graphql/stream
      protocol: sse
  - name: github-adapter
    routing_url: http://localhost:3005/graphql
    # No subscriptions for GitHub adapter